In [1]:
import numpy as np
import pandas as pd

In [2]:
arr=np.full((2,3),5)

In [3]:
print(arr)

[[5 5 5]
 [5 5 5]]


In [6]:
a=np.array([1,2,3,4,5])
print(a[2])
print(a[2]+a[3])

3
7


In [14]:
a=np.array(([1,2,3,4,5,6],[4,5,6,4,7,8]))
print(a[0,4])

5


In [24]:
a=np.array(([[1,2,3,4,5,6],[4,5,6,4,7,8]],[[1,2,3,4,5,6],[4,5,6,7,9,1]]))
print(a)
print(a[0,1,2])
print(a[1,1,4])
print(a[1,1,-1])

[[[1 2 3 4 5 6]
  [4 5 6 4 7 8]]

 [[1 2 3 4 5 6]
  [4 5 6 7 9 1]]]
6
9
1


In [28]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[2:5])
print(a[:5])
print(a[2:9:5])
print(a[2::2])

[3 4 5]
[1 2 3 4 5]
[3 8]
[3 5 7 9]


In [29]:
arr=np.array([[1,2,3,4,5],[6,4,5,7,5]])

In [34]:
print(arr[1,:])
print(arr[:,:])
print(arr[:3,4:])

[6 4 5 7 5]
[[1 2 3 4 5]
 [6 4 5 7 5]]
[[5]
 [5]]


In [40]:
a=np.array([[[1,2,4,5],[1,2,3,4],[4,6,7,5]],[[4,5,6,7],[7,8,9,7],[4,56,4,5]]])

In [41]:
print(a)

[[[ 1  2  4  5]
  [ 1  2  3  4]
  [ 4  6  7  5]]

 [[ 4  5  6  7]
  [ 7  8  9  7]
  [ 4 56  4  5]]]


In [ ]:
print(a.shape)

(2, 3, 4)


In [45]:
print(a[0,2,2])

7


In [55]:
x=np.zeros((2,3,4))
x1=np.ones((2,3,4))

print(x)
print(x1)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [62]:
a=np.array([1,23,3,46,5])
c=a.copy()
d=a.view()
b=a
b[2]=45
print(a)
c[2]=46
print(a)
print(c)
d[2]=23
print(d)
print(a)

[ 1 23 45 46  5]
[ 1 23 45 46  5]
[ 1 23 46 46  5]
[ 1 23 23 46  5]
[ 1 23 23 46  5]


In [74]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.reshape(3,3))
print(arr.reshape(3,3).base)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [75]:
arr=np.array([1,2,3,4],ndmin=5)

In [76]:
print(arr)

[[[[[1 2 3 4]]]]]


In [81]:
arr=np.array([1,2,30],[4,5,6])
for i in arr:
    for j in arr:
        print(j)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [83]:
a="alskaj"
print(a.split)

<built-in method split of str object at 0x000001DC10508B40>
