In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5])
a[1],a[4],a[0],a[3]=a[4],a[1],a[3],a[0]
print(a)

[4 5 3 1 2]


In [14]:
arr2=np.array([[1,2,3,4,5],[7,8,9,5,6],[11,12,13,21,14]])
print(arr2)
arr2[[0,2],:]=arr2[[2,0],:]
arr2[:,[2,3,4]]=arr2[:,[4,3,2]]
print(arr2)

[[ 1  2  3  4  5]
 [ 7  8  9  5  6]
 [11 12 13 21 14]]
[[11 12 14 21 13]
 [ 7  8  6  5  9]
 [ 1  2  5  4  3]]


In [22]:
arr3=np.array(
    [
    [
        [4,5,6],
        [7,9,5]
    ],
    [
        [8,9,1],
        [7,4,1]
    ]
    ]
)
print(arr3)
arr3[:,[0,1],:]=arr3[:,[1,0],:]
print(arr3)
arr3[[0,1],[0,1],:]=arr3[[1,0],[1,0],:]
print(arr3)

[[[4 5 6]
  [7 9 5]]

 [[8 9 1]
  [7 4 1]]]
[[[7 9 5]
  [4 5 6]]

 [[7 4 1]
  [8 9 1]]]
[[[8 9 1]
  [4 5 6]]

 [[7 4 1]
  [7 9 5]]]


In [25]:
arr4=np.array([1,2,np.nan,5,np.nan])
isnan=np.isnan(arr4)
print(isnan)
arr5=arr4[~np.isnan(arr4)]
print(arr5)
res=np.nan_to_num(arr4,copy=True,nan=0)
print(res)

[False False  True False  True]
[1. 2. 5.]
[1. 2. 0. 5. 0.]


In [30]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
np.save('data.npy',a)
res=np.load('data.npy')
print(res)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [34]:
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],[7,8,9]])
np.savez('data2.npz',a=arr1,b=arr2)
res=np.load('data2.npz')
print(res['a'])
print(res['b'])

[1 2 3]
[[1 2 3]
 [7 8 9]]


In [35]:
with open('data6.txt','w') as f:
    f.write("1 2 3 \n 4 5 0")
data=np.loadtxt('data6.txt')
print(data)

[[1. 2. 3.]
 [4. 5. 0.]]


In [38]:
with open('data2.csv','w') as f:
    f.write("1,2,3 \n 4,5,0")
data=np.genfromtxt('data2.csv',delimiter=",")
print(data)

[[1. 2. 3.]
 [4. 5. 0.]]


In [43]:
arr1=np.array([[-3,2],[1,-2]]) # 3x+2y and x+2y
arr2=np.array([5,5]) # these are constant so the full equation is 3x+2y=5 and x+2y=5
res=np.linalg.solve(arr1,arr2)
print(res)

[-5. -5.]


In [45]:
arr1_inv=np.linalg.inv(arr1)
print(arr1_inv)
res=np.dot(arr1_inv,arr2)
print(res)

[[-0.5  -0.5 ]
 [-0.25 -0.75]]
[-5. -5.]
