In [2]:
import numpy as np
a=np.array([[1,2,3],[7,8,9],[6,4,5]])
res=np.transpose(a)
print(res)

[[1 7 6]
 [2 8 4]
 [3 9 5]]


In [3]:
a=np.array([8,8,9])
b=np.array([7,8,9])
res=np.concat([a,b])

In [4]:
print(res)

[8 8 9 7 8 9]


In [5]:
a=np.array([[1,2,3],[7,8,9]])
b=np.array([[4,5,6],[8,9,10]])
res=np.concatenate([a,b],axis=0)
res1=np.concatenate([a,b],axis=1)
print(res)
print(res1)

[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [ 8  9 10]]
[[ 1  2  3  4  5  6]
 [ 7  8  9  8  9 10]]


In [6]:
a=np.arange(9)
print(a)
res=np.split(a,3)
print(res)

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [7]:
for i ,arr in enumerate(res):
    print(i+1)
    print(arr)

1
[0 1 2]
2
[3 4 5]
3
[6 7 8]


In [8]:
a=np.array([[1,2,3],[4,5,5]])
print(a.shape)
res=np.resize(a,(3,2))
print(res)

(2, 3)
[[1 2]
 [3 4]
 [5 5]]


In [9]:
res2=np.resize(a,(3,3))
print(res2)

[[1 2 3]
 [4 5 5]
 [1 2 3]]


In [10]:
res=np.append(a,[[7,8,9],[8,9,10]],axis=0)
res1=np.append(a,[[7,8,9],[8,9,10]],axis=1)
print(res)
print(res1)

[[ 1  2  3]
 [ 4  5  5]
 [ 7  8  9]
 [ 8  9 10]]
[[ 1  2  3  7  8  9]
 [ 4  5  5  8  9 10]]


In [11]:
a=np.array([[1,2],[3,4],[7,8]])
print(a)
res=np.insert(a,3,[11,12])
print(res)
print(a)

[[1 2]
 [3 4]
 [7 8]]
[ 1  2  3 11 12  4  7  8]
[[1 2]
 [3 4]
 [7 8]]


In [12]:
a=np.arange(12)
print(a)
a=a.reshape(3,4)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
a=np.delete(a,6)
print(a)
print(np.delete(a,7))

[ 0  1  2  3  4  5  7  8  9 10 11]
[ 0  1  2  3  4  5  7  9 10 11]


In [ ]:
a=np.array([24,11,2,3])
print(a)
res=np.flip(a)
res1=np.sort(a)
print(res)
print(res1)


[24 11  2  3]
[ 3  2 11 24]
[ 2  3 11 24]


In [23]:
a=np.arange(24)
a.ndim
print(a)
print(a.reshape(2,3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [30]:
a=np.array([
    [[1,2,3],[2,3,4]],
    [[1,23,4],[7,8,9]]
],dtype=np.float32)
print(a.size)
print(a.shape)

12
(2, 2, 3)


In [31]:
print(a.dtype)

float32


In [34]:
a=np.array([[11,21,12],[45,46,42]])
b=np.array([[11,21,12],[4,5,6]])
print(a+b)
print(a*b)
print(a/b)
print(a-b)
print(a%b)

[[22 42 24]
 [49 51 48]]
[[121 441 144]
 [180 230 252]]
[[ 1.    1.    1.  ]
 [11.25  9.2   7.  ]]
[[ 0  0  0]
 [41 41 36]]
[[0 0 0]
 [1 1 0]]


In [ ]:
a=np.array