In [ ]:
import pandas as pd
import numpy as np

In [2]:
a=[[6, -8, 73, -110], [np.nan, -8, 0, 94]]
a=np.array(a)
print(a,type(a))

[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]] <class 'numpy.ndarray'>


In [3]:
arr=np.nan_to_num(a,0)
print(arr)

[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]


In [6]:
arr=arr.T
print(arr)

[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [11]:
a = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
a=np.array(a)

print(a.shape)
a=np.moveaxis(a,0,2)

(2, 2, 2)


In [12]:
arr = np.array([1, -2, 3, -4, 5])
arr[arr < 0] = 0
print(arr)

[1 0 3 0 5]


In [14]:
arr = np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]
])
print(arr)
col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])
print(arr)

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]
