In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,45,6])
res=arr.reshape(2,4)
print(res.shape)
print(res.dtype)
print(res.itemsize)
print(res)

(2, 4)
int64
8
[[ 1  2  3  4]
 [ 5  6 45  6]]


In [4]:
arr=np.full((3,3),9)

In [5]:
res=np.arange(25,125,10)
print(res)

[ 25  35  45  55  65  75  85  95 105 115]


In [6]:
arr=np.array([1,23,3,5])
rever_arr=arr[::-1]
print(rever_arr)
print(arr)

[ 5  3 23  1]
[ 1 23  3  5]


In [11]:
res=np.arange(48)
res=res.reshape(4,4,3)
res1=res[1,0,-1]
print(res1)

14


In [16]:
res=np.arange(16)
res=res.reshape(4,4)
print(res)

print("Odd Rows and even Columns")
res1=res[::2,1::2]
print(res1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Odd Rows and even Columns
[[ 1  3]
 [ 9 11]]


In [17]:
arr=np.arange(48)
res=arr.reshape(4,4,3)
result=res[1,:2,:2]
print(result)

[[12 13]
 [15 16]]


In [26]:
arr=np.array([[23, 56, 78, 93],[71, 82,13, 24]])
for i in range(len(arr)):
    for j in range(len(arr[i])):
        if arr[i][j]%2 != 0:
            arr[i][j]=-1
print(arr)
            

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [28]:
arr=np.array([1, 0, 2, 0, 3, 0, 4])
for i in range(len(arr)):
    if(arr[i]!=0):
        print(i)
res=arr.nonzero()
print(res)

0
2
4
6
(array([0, 2, 4, 6]),)


In [32]:
arr=np.array([[1,2,3,4],[4,5,6,4]])
arr2=np.array([[7,8,9,4],[4,5,6,8]])
res=arr+arr2
res2=arr*arr2
print(res)
print(res2)

[[ 8 10 12  8]
 [ 8 10 12 12]]
[[ 7 16 27 16]
 [16 25 36 32]]


In [34]:
arr1 = np.array([15, 20, 25])
arr2 = np.array([10,40,37])
res=np.dot(arr1,arr2)
print(res)

1875
