In [1]:
import numpy  as np

In [16]:
arr1=[[1,2,3],[4,5,6]]
arr2=[[5,6,4],[8,9,6]]
arr1=np.array(arr1)
arr2=np.array(arr2)
result=np.concat((arr1,arr2),axis=1)
result1=np.concatenate((arr1,arr2),axis=1)
print(result)
print(result1)

[[1 2 3 5 6 4]
 [4 5 6 8 9 6]]
[[1 2 3 5 6 4]
 [4 5 6 8 9 6]]


In [8]:
arr=[[1,2,3],[4,5,6]]
arr=np.array(arr)
print(arr)
print(arr.shape)
print(arr.reshape(-1))

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]


In [18]:
arr3=np.array([[1,2,3],[4,5,6]])
res2=np.flip(arr3)
print(res2)

[[6 5 4]
 [3 2 1]]


Question 4

In [31]:
arr4=np.array([[1,23,4],[45,6,1]])
arr5=np.array([1,23,4])
arr6=np.array([10,3,41])
sum=0
res=np.max(arr4)
res1=np.min(arr4)
res2=arr4.shape[0] # for rows
res3=arr4.shape[1] # for columns
for i in arr4:
    sum=sum+i
res4=arr5+arr6
res5=arr5-arr6
res6=arr5*arr6
res7=arr5/arr6
print(sum)
print(res)
print(res1)
print(res2)
print(res3)
print(res4)
print(res5)
print(res6)
print(res7)

[46 29  5]
45
1
2
3
[11 26 45]
[ -9  20 -37]
[ 10  69 164]
[0.1        7.66666667 0.09756098]


In [37]:
arr7=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[8,4,5]]])
for i in arr7:
    for j in i:
        for k in j:
            print(k)
for x in np.nditer(arr7):
    print(x)

1
2
3
4
5
6
7
8
9
8
4
5
1
2
3
4
5
6
7
8
9
8
4
5


In [33]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
for row in arr_2d: 
    print(row) 

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
arr1 = np.array([3, 4]) 
arr2 = np.array([1, 0])
avg = ((arr1 + arr2) / 2 )
print(avg)
res=np.mean(avg)
res1=np.median(avg)
print(res)
print(res1)

[2. 2.]
2.0
2.0
