In [2]:
import numpy as np


In [3]:
arr=np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])
np.nan_to_num(arr,0)
print(arr)

[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]


In [4]:
arr = np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

np.moveaxis(arr,0,2)

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [5]:
arr=np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])
print(arr)

[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]


In [6]:
col_mean=np.nanmean(arr,axis=0)
rows,col=np.where(np.isnan(arr))
arr[rows,col]=col_mean

ValueError: shape mismatch: value array of shape (4,) could not be broadcast to indexing result of shape (1,)